In [1]:
import numpy as np
array=np.random.randint(1,100,9)
array

array([69, 82, 26, 46, 64, 44, 96, 48, 81])

In [2]:
np.sqrt(array)

array([8.30662386, 9.05538514, 5.09901951, 6.78232998, 8.        ,
       6.63324958, 9.79795897, 6.92820323, 9.        ])

In [3]:
array.ndim

1

In [5]:
new_array=array.reshape(3,3)
new_array

array([[69, 82, 26],
       [46, 64, 44],
       [96, 48, 81]])

In [6]:
new_array.ndim

2

In [7]:
new_array.ravel()

array([69, 82, 26, 46, 64, 44, 96, 48, 81])

In [9]:
newm=new_array.reshape(3,3)
newm

array([[69, 82, 26],
       [46, 64, 44],
       [96, 48, 81]])

In [10]:
newm[2,1:3]

array([48, 81])

In [11]:
newm[1:2,1:3]

array([[64, 44]])

In [12]:
new_array[0:3,0:0]

array([], shape=(3, 0), dtype=int32)

In [13]:
new_array[0:2,0:1]

array([[69],
       [46]])

In [14]:
new_array[0:3,0:1]

array([[69],
       [46],
       [96]])

In [15]:
new_array[1:3]

array([[46, 64, 44],
       [96, 48, 81]])